package hospitalmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ExpencesAndIncomes extends javax.swing.JFrame {

 /**
  * Creates new form ExpencesAndIncomes
  */
 double expTotal;
 double incTotal;
 private double total;
 boolean check =false;


 public ExpencesAndIncomes() {
  initComponents();
  connect();
  displayOnTable();
 }
 Connection con;
 PreparedStatement pst;
 ResultSet rs;

 /**
  * this metod is used for show information from database onthe jTable
  */
 public void connect()
 {
  try {
   Class.forName("com.mysql.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost/hospitalmanagementsystem", "root", "");
  } catch (ClassNotFoundException e) {
   // TODO Auto-generated catch block
   e.printStackTrace();
  } catch (SQLException e) {
   // TODO Auto-generated catch block
   e.printStackTrace();
  }
 }
 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
 private void initComponents() {

  jPanel2 = new javax.swing.JPanel();
  jPanel1 = new javax.swing.JPanel();
  expensesAndIncomeHeaderLabel = new javax.swing.JLabel();
  expensesLabel = new javax.swing.JLabel();
  incomesLabel = new javax.swing.JLabel();
  expencesText = new javax.swing.JTextField();
  incomeText = new javax.swing.JTextField();
  addButton = new javax.swing.JButton();
  backButton = new javax.swing.JButton();
  jScrollPane1 = new javax.swing.JScrollPane();
  jTable1 = new javax.swing.JTable();
  jLabel1 = new javax.swing.JLabel();
  totalOfTotal = new javax.swing.JLabel();

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 100, Short.MAX_VALUE)
    );
  jPanel2Layout.setVerticalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 100, Short.MAX_VALUE)
    );

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setPreferredSize(new java.awt.Dimension(1000, 550));

  jPanel1.setBackground(new java.awt.Color(51, 153, 255));

  expensesAndIncomeHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
  expensesAndIncomeHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  expensesAndIncomeHeaderLabel.setText("EXPENSES  /  INCOMES");

  expensesLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
  expensesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  expensesLabel.setText("Expenses");

  incomesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
  incomesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  incomesLabel.setText("Incomes");

  expencesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
  expencesText.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    expencesTextActionPerformed(evt);
   }
  });

  incomeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
  incomeText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
  incomeText.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    incomeTextActionPerformed(evt);
   }
  });

  addButton.setBackground(new java.awt.Color(51, 102, 255));
  addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
  addButton.setText("ADD");
  addButton.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    addButtonActionPerformed(evt);
   }
  });

  backButton.setBackground(new java.awt.Color(51, 102, 255));
  backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
  backButton.setText("BACK");
  backButton.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    backButtonActionPerformed(evt);
   }
  });

  jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
      "Expenses", "Incomes", "Current Total"
    }
    ) {
   Class[] types = new Class [] {
     java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
   };

   public Class getColumnClass(int columnIndex) {
    return types [columnIndex];
   }
  });
  jScrollPane1.setViewportView(jTable1);

  jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
  jLabel1.setText("TOTAL:");

  totalOfTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel1Layout.createSequentialGroup()
      .addGap(400, 400, 400)
      .addComponent(expensesAndIncomeHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addGroup(jPanel1Layout.createSequentialGroup()
      .addGap(34, 34, 34)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addComponent(expensesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(expencesText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(49, 49, 49)
          .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addComponent(incomesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(incomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
      .addGap(18, 18, 18)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(91, 91, 91))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(totalOfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(150, 150, 150))))
    );
  jPanel1Layout.setVerticalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel1Layout.createSequentialGroup()
      .addGap(45, 45, 45)
      .addComponent(expensesAndIncomeHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(68, 68, 68)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(expencesText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(expensesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(incomesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(incomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(118, 118, 118)
          .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(totalOfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGap(70, 70, 70))
    );

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, Short.MAX_VALUE)
    );
  layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 550));
  setResizable(true);
  setSize(new java.awt.Dimension(1000, 575));
  setLocationRelativeTo(null);
 }// </editor-fold>      
 /**
  * this metod is used for show information from database onthe jTable
  */
 public void displayOnTable(){

  try {
   pst = con.prepareStatement("select * from fund");
   rs = pst.executeQuery();
   ResultSetMetaData rsmd = rs.getMetaData();
   int columns = rsmd.getColumnCount();


   DefaultTableModel def = (DefaultTableModel)jTable1.getModel();
   def.setRowCount(0);
   double totals = 0;
   while(rs.next()){

    Vector vec = new Vector();
    for(int i = 1; i <= columns; i++){

     vec.add(rs.getDouble("expenses"));
     vec.add(rs.getDouble("incomes"));
     vec.add(rs.getDouble("total"));
     totals = rs.getDouble("total");
    }
    def.addRow(vec);

    totalOfTotal.setText("" + totals);
   }


  } catch (SQLException ex) {
   Logger.getLogger(ExpencesAndIncomes.class.getName()).log(Level.SEVERE, null, ex);
  }

 }
 private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
  double tot = 0;
  int count = 0;
  try{

   pst = con.prepareStatement("select * from fund");
   rs = pst.executeQuery();
   if(!check){
    while(rs.next())
    {

     System.out.println("bura");
     tot = rs.getDouble("total");
     count++;


    }
   }
   else{
    tot=0;
    check =false;
   }

  }
  catch(Exception e){
   e.printStackTrace();
  }


  double expense = Double.parseDouble(expencesText.getText());
  double income = Double.parseDouble(incomeText.getText());

  // incTotal += income;
  // expTotal += expense;

  //   total = incTotal - expTotal;
  total = income- expense; 
  total = total+tot;

  double toplam = 0;
  connect();
  try {
   ResultSetMetaData rsmd = rs.getMetaData();
   int columns = rsmd.getColumnCount();
   while(rs.next()){
    double result = rs.getDouble("total");
    toplam += result;
    System.out.println(toplam);

   }
   pst = con.prepareStatement("insert into fund(expenses,incomes,total)values(?,?,?)");
   pst.setDouble(1, expense);
   pst.setDouble(2, income);
   pst.setDouble(3, total);

   pst.executeUpdate();

   expencesText.setText("");
   incomeText.setText("");
   totalOfTotal.setText(""+total);
  } catch (SQLException ex) {
   Logger.getLogger(ExpencesAndIncomes.class.getName()).log(Level.SEVERE, null, ex);
  }
  displayOnTable();
 }                                         

 private void expencesTextActionPerformed(java.awt.event.ActionEvent evt) {                                             
  // TODO add your handling code here:
 }                                            

 private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
  this.setVisible(false);
 }                                          

 private void incomeTextActionPerformed(java.awt.event.ActionEvent evt) {                                           
  // TODO add your handling code here:
 }                                          

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(ExpencesAndIncomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(ExpencesAndIncomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(ExpencesAndIncomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(ExpencesAndIncomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new ExpencesAndIncomes().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify                     
 private javax.swing.JButton addButton;
 private javax.swing.JButton backButton;
 private javax.swing.JTextField expencesText;
 private javax.swing.JLabel expensesAndIncomeHeaderLabel;
 private javax.swing.JLabel expensesLabel;
 private javax.swing.JTextField incomeText;
 private javax.swing.JLabel incomesLabel;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JTable jTable1;
 private javax.swing.JLabel totalOfTotal;
 // End of variables declaration                   
}
